### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by williambj1** [williambj1/Hackintosh-Asus-ROG-Laptop-Coffee-Lake#1]
- [ ] Check Sound Card path maps & nodes via special Windows drivers
  - https://github.com/torvalds/linux/commit/4e051106730dfc640a8b49db88440af304726f4d
  - [AppleHDA-for-ALC294.zip](https://github.com/williambj1/Hackintosh-EFI-Asus-Zephyrus-S-GX531/files/4352483/AppleHDA-for-ALC294.zip)
- [ ] Workaround for USTP patch
- [ ] Latest OpenCore won't boot into Installation and Recovery
